### PR TITLE
Fix hueristics bug

### LINKED ISSUE #317: Hueristics not working properly
I get the following even when I have a USB Tessel connected:

```
➜  t2-demo  t2 run index.js --name Frank
INFO Looking for your Tessel...
INFO Please specify a Tessel by name [--name <tessel name>]
```

### PR DESCRIPTION
**Pull request by johnnyman727**
Fixes #317.

### CODE REVIEW

File: lib/controller.js [hunk 1]
```diff
@@ -61,21 +61,24 @@ Tessel.list = function(opts) {
...
+          // Figure out which Tessel will be selected
+          controller.runHeuristics(opts, reconciledTessels)
+            .then(function logSelected(tessel) {
+              // Report that selected Tessel to the user
+              logs.info('Multiple Tessels found.');
+              if (tessel) {
+                logs.info('Will default to', tessel.name, '.');
+              }
+              // Helpful instructions on how to switch
+              logs.info('Set default Tessel with environment variable (e.g. \'export TESSEL=bulbasaur\') or use the --name flag.');
```
Comment (rwaldron) [inline lib/controller.js]: nit: Instead of `\'`, just use `"`

**Comment by johnnyman727** [comment]
@rwaldron could you review when you get a chance?

This PR fixes two things:
1. If multiple LAN Tessels were discovered, the heuristics function would claim that it couldn't deduce which Tessel to use even if a usb Tessel was connected.
2. The heuristics function weirdly returned nothing if it could deduce which Tessel to use. This PR fixes change those cases so that an error is `Promise.reject`ed which I believe is a bit more sanitary.

**Comment by rwaldron** [comment]
LGTM!

(Great tests!)
