### PR TITLE
Temporarily fixes code deploy to flash

### LINKED ISSUE #495: Deployments to /app/ over USB hang
I am able to deploy a 600kb over USB to RAM (on `/tmp`) but when I try to deploy to Flash (on `/app`), the deploy hangs after only 138.7kB are transferred.

### PR DESCRIPTION
**Pull request by johnnyman727**
For some reason, USB writes to Flash storage would freeze after about 100k. This does not happen if the deploy is slower. I'm not sure why but it appears to be a race condition in the USB Daemon.

This PR is certainly not ideal, but it will be a faster patch than trying to figure out a race condition in C code. All it does is write code to RAM first regardless of `push` or `run`, then copy it into Flash if it was a `push` prior to running it.

Suggestions/thoughts are welcomed.

Fixes #495.

### CODE REVIEW

**Comment by rwaldron** [comment]
With `t2 push <file> --usb`, I deployed the following program:

```js
var tessel = require('tessel');
var express = require('express');
var index = Math.round(Math.random() * 3);

// Turn them all off, then turn one on
tessel.leds.off()[index].on();

setTimeout(function () {
  tessel.close();
  process.exit();
}, 10000);

console.log("LED %d is on.", index);
```


When I allow a deployment to run to completion before redeploying with the same command, the `t2 push <file> --usb` operation is inconsistently successful:


```
rwaldron at new-host-4 in ~/robotz/tessel-init
$ t2 push deployment.js --usb
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Generating slim build.
INFO Writing project to Flash on bishop (235.008 kB)...
INFO Deployed.
INFO You may now disconnect from the Tessel. Your code will be run whenever Tessel boots up. To remove this code, use `tessel erase`.
INFO Running bundled project...
rwaldron at new-host-4 in ~/robotz/tessel-init
$ t2 push deployment.js --usb
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Generating slim build.
INFO Writing project to Flash on bishop (235.008 kB)...
INFO Deployed.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error upon remote process exit: 1
    at USBProcess.<anonymous> (/Users/rwaldron/clonez/t2-cli/lib/usb/usb_process.js:58:26)
    at USBProcess.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at USBProcess.emit (events.js:169:7)
    at Parser.<anonymous> (/Users/rwaldron/clonez/t2-cli/lib/usb/usb_daemon.js:127:14)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/Users/rwaldron/clonez/t2-cli/node_modules/usb-daemon-parser/index.js:152:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:110:10)
rwaldron at new-host-4 in ~/robotz/tessel-init
$ t2 push deployment.js --usb
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Generating slim build.
INFO Writing project to Flash on bishop (235.008 kB)...
INFO Deployed.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error upon remote process exit: 1
    at USBProcess.<anonymous> (/Users/rwaldron/clonez/t2-cli/lib/usb/usb_process.js:58:26)
    at USBProcess.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at USBProcess.emit (events.js:169:7)
    at Parser.<anonymous> (/Users/rwaldron/clonez/t2-cli/lib/usb/usb_daemon.js:127:14)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/Users/rwaldron/clonez/t2-cli/node_modules/usb-daemon-parser/index.js:152:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:110:10)
rwaldron at new-host-4 in ~/robotz/tessel-init
$ t2 push deployment.js --usb
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Generating slim build.
INFO Writing project to Flash on bishop (235.008 kB)...
INFO Deployed.
INFO You may now disconnect from the Tessel. Your code will be run whenever Tessel boots up. To remove this code, use `tessel erase`.
INFO Running bundled project...
```

The same behavior exists when I run `t2 push <file> --usb` while a script is currently running.

Here is a longer series of deployments: https://gist.github.com/rwaldron/35c26ffb00c6be697f60

**Comment by johnnyman727** [comment]
Thanks! I will try to reproduce.

**Comment by johnnyman727** [comment]
Can reproduce. Will investigate...

File: lib/tessel/deploy.js [hunk 1]
```diff
@@ -594,7 +604,7 @@ actions.writeToFile = function(t, entryPoint) {
       // If it was opened successfully
       .then(function(remoteProcess) {
         // When the remote process finishes
-        remoteProcess.stdin.once('finish', function() {
+        remoteProcess.once('close', function() {
```
Comment (johnnyman727) [inline lib/tessel/deploy.js]: We should wait for the entire process to close to be sure the file was saved. Otherwise, we could see intermittent failures where we have finished writing data to stdin but the file has not yet been saved.

File: lib/usb/usb_process.js [hunk 2]
```diff
@@ -5,6 +5,7 @@ var util = require('util');
 
 // Third Party
 var protocol = require('usb-daemon-parser');
+var debug = require('debug')('usb_process');
```
Comment (johnnyman727) [inline lib/usb/usb_process.js]: The changes in this file aren't necessary for this fix but the debugging aid will be useful in the future.

File: lib/tessel/deploy.js (hunk 1 above)
Comment (rwaldron) [inline lib/tessel/deploy.js]: Oh, interesting

File: lib/usb/usb_process.js [hunk 3]
```diff
@@ -149,6 +151,14 @@ util.inherits(RemoteWritableStream, stream.Writable);
 
 // The underlying function for .write calls on the Node stream
 RemoteWritableStream.prototype._write = function(chunk, enc, callback) {
+  // Purely for debugging purposes
+  // If this is a control Stream
+  if (this.writeHeaderFunc === protocol.controlWrite) {
+      // Save the string we're writing for debugging
+      this.process.commandString = chunk.toString();
+      debug('Opening process for', this.process.commandString);
```
Comment (rwaldron) [inline lib/usb/usb_process.js]: nit pick: this indentis too far

**Comment by rwaldron** [comment]
With the same program used previously, I did 10 deployments each: 

- allow a deployment to run to completion before redeploying with the same command
- run `t2 push <file> --usb` while a script is currently running

And observed no failures. 

Just fix that one weird indent thing and this is good to land!
