### PR TITLE
[WIP] Fixing provisioning issues

### LINKED ISSUE #213: Improper provisioning logic
If you have two Tessels, and you provision the first, everything works as expected. However, if you then try to provision the second, the CLI will give a warning that the keys already exist and not provision it.

It should realize the keys already exist and continue to provision the second device.

### LINKED ISSUE #214: Can't provision Tessels already on LAN
If a Tessel is already connected to a LAN (perhaps someone else was using it), and you plug in USB to provision it, the provisioning will fail. This is because the discovery of Tessel prefers LAN devices and there is currently no good way to fetch a USB connection (if it's connected over both).

### PR DESCRIPTION
**Pull request by johnnyman727**
FIxes #213 and fixed #214. 

In the midst of fixing tests...

### CODE REVIEW

File: lib/controller.js [hunk 1]
```diff
@@ -355,7 +355,8 @@ controller.provisionTessel = function(opts) {
             }
           });
         } else {
-          reject('Keys already exist. Refusing to overwrite them.');
+          // ~/.tessel exists with keys
+          resolve();
```
Comment (rwaldron) [inline lib/controller.js]: The tests needs to be updated for this.

Comment (johnnyman727) [inline lib/controller.js]: Yes, I'm in the midst of adding it and fixing the other tests but it's been more involved than I expected.

Comment (rwaldron) [inline lib/controller.js]: No worries, I can help get them updated.
